
[build]
  command = "./build.sh"
  publish = "dist"

[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_CDA_TOKEN = "change me"
  CONTENTFUL_CMA_TOKEN = "change me"
  CONTENTFUL_SPACE = "change me"
